version: "3.9"
services:
  api:
    build: .
    container_name: dlopt_api
    env_file: .env
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - PYTHONPATH=/app          # <-- добавьте эту строку
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

  worker:
    build: .
    container_name: dlopt_worker
    env_file: .env
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - PYTHONPATH=/app          # <-- добавьте эту строку
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    command: ["celery", "-A", "worker.celery_app:celery_app", "worker", "--loglevel=INFO"]

  redis:
    image: redis:7
    container_name: dlopt_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
